import Head from 'next/head'

const MetaTags = () => {
  return (
    <Head>
      <title>Chris Achinga</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  )
}

export default MetaTags
