import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chris Achinga</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This is{' '}
          <a href='https://www.linkedin.com/in/chrisachinga/'>Chris Achinga</a>
        </h1>

        <p className={styles.description}>
          Welcome <code className={styles.code}>to my portfolio. About Me</code>
        </p>

        <div className={styles.grid}>
          <a
            href='https://docs.google.com/document/d/14rkWMF1pL1qF5eaQdFS0Na6CP0Y2yEv-1NPsuPOLZa8/edit?usp=sharing'
            className={styles.card}
          >
            <h2>Resume &rarr;</h2>
            <p>My detailed CV and Resume</p>
          </a>

          <a href='https://github.com/achingachris/' className={styles.card}>
            <h2>GitHub &rarr;</h2>
            <p>My Projects and Open Source Codes</p>
          </a>

          <a
            href='https://www.linkedin.com/in/chrisachinga/'
            className={styles.card}
          >
            <h2>LinkedIN &rarr;</h2>
            <p>My Professional Updates</p>
          </a>

          <a
            href='https://www.getrevue.co/profile/achinga_chris'
            className={styles.card}
          >
            <h2>Newsletter &rarr;</h2>
            <p>Subscribe to get bi-weekly updates about all tech</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
